version: "3.9"

services:

  stage:
    image: iocchi/stage_environments
    container_name: stage
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/home/robot/.Xauthority
    entrypoint:
    - bash
    - -ci
    - "sleep 5 && rosrun stage_environments start_simulation.py --tmux --server -server_port 9235"

  navigation:
    image: iocchi/marrtino:navigation
    container_name: navigation
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    - ROBOT_TYPE=$ROBOT_TYPE

  speech:
    image: iocchi/marrtino:speech
    container_name: speech
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - ROS_IP=$ROS_IP
    volumes:
    - /dev:/dev

  vision:
    image: iocchi/marrtino:vision
    container_name: vision
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    - CAMRES=$CAMRES
    volumes:
    - /dev:/dev

  stagepersondetection:
    image: iocchi/stagepersondetection
    container_name: stagepersondetection
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    entrypoint:
    - bash
    - -ci
    - "python3 stageperson_net.py -modelname spd --server -server_port 9250"

  actions:
    image: iocchi/marrtino:base
    container_name: actions
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $DEMO_DIR:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 10 && cd ~/src/DIAG_demo/bin && ./init.bash"

  pnp:
    image: iocchi/pnp
    container_name: pnp
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $DEMO_DIR:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 10 && roscd pnp_ros && ./init.bash"


