version: "3.9"

services:

  xserver:
    image: devrt/xserver
    container_name: xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:1
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20

  stage:
    image: iocchi/stage_environments
    container_name: stage
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=:1
    - ROS_IP=$ROS_IP
    volumes_from:
    - xserver
    entrypoint:
    - bash
    - -ci
    - "rosrun stage_environments start_simulation.py --tmux --server -server_port 9235"

  navigation:
    image: iocchi/marrtino:navigation
    container_name: navigation
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    - ROBOT_TYPE=$ROBOT_TYPE

  speech:
    image: iocchi/marrtino:speech
    container_name: speech
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - ROS_IP=$ROS_IP
    volumes:
    - /dev:/dev

  actions:
    image: iocchi/marrtino:base
    container_name: actions
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $DEMO_DIR:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 5 && cd ~/src/DIAG_demo/bin && ./init.bash"

  pnp:
    image: iocchi/pnp
    container_name: pnp
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $DEMO_DIR:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 10 && roscd pnp_ros && ./init.bash"

