version: "3.9"

services:

  stage:
    image: iocchi/stage_environments
    container_name: stage
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/home/robot/.Xauthority
    - $HOME/src/stage_environments:/home/robot/src/stage_environments
    entrypoint:
    - bash
    - -ci
    - "sleep 5 && rosrun stage_environments start_simulation.py --tmux --server -server_port 9235"

  navigation:
    image: marrtino:navigation
    build:
      context: $MARRTINO_APPS_HOME/docker
      dockerfile: Dockerfile.navigation
    container_name: navigation
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - ROS_IP=$ROS_IP
    - ROBOT_TYPE=$ROBOT_TYPE
    volumes:
    - /dev:/dev
    - $MARRTINO_APPS_HOME:/home/robot/src/marrtino_apps
    - $HOME/src/gradient_based_navigation:/home/robot/src/gradient_based_navigation

  speech:
    image: marrtino:speech
    build:
      context: $MARRTINO_APPS_HOME/docker
      dockerfile: Dockerfile.speech
    container_name: speech
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - ROS_IP=$ROS_IP
    volumes:
    - /dev:/dev
    - $MARRTINO_APPS_HOME:/home/robot/src/marrtino_apps

  vision:
    image: marrtino:vision
    build:
      context: $MARRTINO_APPS_HOME/docker
      dockerfile: Dockerfile.vision
    container_name: vision
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    - CAMRES=$CAMRES
    volumes:
    - /dev:/dev
    - $MARRTINO_APPS_HOME:/home/robot/src/marrtino_apps

  stagepersondetection:
    image: iocchi/stagepersondetection
    container_name: stagepersondetection
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    volumes:
    - $HOME/src/stagepersondetection:/home/robot/src/stagepersondetection
    entrypoint:
    - bash
    - -ci
    - "python3 stageperson_net.py -modelname spd --server -server_port 9250"


  actions:
    image: marrtino:base
    container_name: actions
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $DEMO_DIR:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 10 && cd ~/src/DIAG_demo/bin && ./init.bash"

  pnp:
    image: iocchi/pnp
    container_name: pnp
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/home/robot/.Xauthority
    - $DEMO_DIR:/home/robot/src/DIAG_demo
    - $HOME/src/PetriNetPlans:/home/robot/src/PetriNetPlans
    entrypoint:
    - bash
    - -ci
    - "sleep 10 && roscd pnp_ros && ./init.bash"


