version: "3.9"

services:

  stage:
    image: iocchi/stage_environments
    container_name: stage
    network_mode: "host"
    tty: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/home/robot/.Xauthority
    entrypoint:
    - bash
    - -ci
    - "rosrun stage_environments start_simulation.py --tmux --server -server_port 9235"

  base:
    image: iocchi/marrtino:base
    container_name: base
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    environment:
    - ROS_IP=$ROS_IP
    volumes:
    - $MARRTINO_APPS_HOME:/home/robot/src/marrtino_apps

  navigation:
    image: iocchi/marrtino:navigation
    container_name: navigation
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - DISPLAY=:0
    - ROS_IP=$ROS_IP
    - ROBOT_TYPE=$ROBOT_TYPE
    volumes:
    - $MARRTINO_APPS_HOME:/home/robot/src/marrtino_apps

  speech:
    image: iocchi/marrtino:speech
    container_name: speech
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    privileged: true
    environment:
    - ROS_IP=$ROS_IP
    volumes:
    - /dev:/dev
    - $MARRTINO_APPS_HOME:/home/robot/src/marrtino_apps

  actions:
    image: iocchi/marrtino:base
    container_name: actions
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $HOME/src/DIAG_demo:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 5 &&cd ~/src/DIAG_demo/bin && ./init.bash"

  pnp:
    image: iocchi/pnp
    container_name: pnp
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    volumes:
    - $HOME/src/DIAG_demo:/home/robot/src/DIAG_demo
    entrypoint:
    - bash
    - -ci
    - "sleep 10 && roscd pnp_ros && ./init.bash"


